font_family      CaskaydiaCove Nerd Font Mono
# font_family      Hack Nerd Font Mono
# font_family      Maple Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
disable_ligatures never

font_size 12.0
modify_font cell_height 150%

window_padding_width 5
include themes/theme.conf
background_opacity 0.40
hide_window_decorations yes
#confirm_os_window_close 0

map ctrl+shift+enter new_window_with_cwd
