set -sg escape-time 0

# enable mouse support
set -g mouse on

# open new window in the same directory as the current window
bind  c  new-window      -c "#{pane_current_path}"
bind  %  split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

# reload config file
unbind r
bind r source-file .tmux.conf \; display "Reloaded!"

# make vim motions: C-h, C-j, C-k, C-l work
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
