color0 #17130e
color1 #ffb4ab
color2 #ffb963
color3 #dfc1a2
color4 #bccd9d
color5 #ffb963
color6 #dfc1a2
color7 #ebe1d9
color8 #9d8e81
color9 #ffb4ab
color10 #ffb963
color11 #dfc1a2
color12 #bccd9d
color13 #ffb963
color14 #dfc1a2
color15 #ebe1d9

cursor                #ebe1d9
cursor_text_color     #17130e
background            #17130e
foreground            #ebe1d9
selection_foreground  #d4c4b5
selection_background  #504539
active_border_color   #ffb963
inactive_border_color #504539
url_color             #ffb963
