# Fonts
font_family family="CaskaydiaCove Nerd Font" style=Thin
bold_font        auto
italic_font      Victor Mono Italic
bold_italic_font Victor Mono Bold Italic

font_size 12.0
enable_ligatures yes

modify_font cell_height 5px
modify_font cell_width 102%

# tabs
tab_bar_style powerline
tab_powerline_style round

# General
editor nvim
enabled_layouts tall:bias=70, stack

# tmux-like
map ctrl+a>\ launch --cwd=current
map ctrl+a>c launch --cwd=current --type=tab
map ctrl+a>n next_tab
map ctrl+shift+h neighboring_window left
map ctrl+shift+l neighboring_window right
map ctrl+a>s goto_session ~/.config/kitty/sessions
map ctrl+a>ctrl+s save_as_session --base-dir ~/.config/kitty/sessions

# sessions
startup_session sessions/default.kitty-session
# hide tabs fror other sessions
tab_bar_filter session:~ or session:^$

# vim-kitty-navigator
map ctrl+h neighboring_window left
map ctrl+j neighboring_window down
map ctrl+k neighboring_window up
map ctrl+l neighboring_window right
map --when-focus-on var:IS_VIM=true ctrl+h
map --when-focus-on var:IS_VIM=true ctrl+j
map --when-focus-on var:IS_VIM=true ctrl+k
map --when-focus-on var:IS_VIM=true ctrl+l

allow_remote_control yes
listen_on unix:@mykitty

# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME
