# Application bindings
$terminal = uwsm app -- ghostty
$browser = omarchy-launch-browser

bindd = SUPER, return, Terminal, exec, $terminal -e tmux
bindd = SUPER_SHIFT, F, File manager, exec, uwsm app -- nautilus --new-window
bindd = SUPER, B, Browser, exec, zen-browser
bindd = SUPER, M, Activity, exec, omarchy-launch-tui btop
bindd = SUPER_SHIFT, T, Activity, exec, ~/.local/bin/todolist.sh

bindd = SUPER_SHIFT, O, Obsidian, exec, omarchy-launch-or-focus obsidian "uwsm app -- obsidian -disable-gpu --enable-wayland-ime"
bindd = SUPER, A, ChatGPT, exec, omarchy-launch-webapp "https://chatgpt.com"
bindd = SUPER, Y, YouTube, exec, omarchy-launch-webapp "https://youtube.com/"

# custom
bindd = SUPER, Q, Close active window, killactive,
bindd = SUPER, F12, Clipboard, exec, walker --modules clipboard
bindd = SUPER, R, Draw region, exec, slurp -d -b "##00000000" -s "##00000044"
bindd = SUPER_SHIFT, R, Draw region, exec, slurp -d -b "##FFFFFF00" -s "##FFFFFF44" -c "##FFFFFFFF"
